export const Users = [
	{
		id: 1,
		profilePicture: "person/1.jpg",
		username: "Michal Tarkay",
	},
	{
		id: 2,
		profilePicture: "person/2.jpg",
		username: "Shlomit Doe",
	},
	{
		id: 3,
		profilePicture: "person/3.jpg",
		username: "Albert James",
	},
	{
		id: 4,
		profilePicture: "person/4.jpg",
		username: "Fernando Ortiz",
	},
	{
		id: 5,
		profilePicture: "person/5.jpg",
		username: "Jasmine Frank",
	},
	{
		id: 6,
		profilePicture: "person/6.jpg",
		username: "Olivia Pastcec",
	},
	{
		id: 7,
		profilePicture: "person/7.jpg",
		username: "Aviv Tarkay",
	},
	{
		id: 8,
		profilePicture: "person/8.jpg",
		username: "Meagan Good",
	},
	{
		id: 9,
		profilePicture: "person/9.jpg",
		username: "Aston Culture",
	},
	{
		id: 10,
		profilePicture: "person/10.jpg",
		username: "Alex Smith",
	},
];

export const Posts = [
	{
		id: 1,
		description: "My beautiful breakfast, i just did LOL!!🤗",
		image: "/posts/1.jpg",
		date: "5 mins ago",
		userId: 1,
		likes: 44,
		comments: 39,
	},
	{
		id: 2,
		description: "Another day coming to an End, thank you Lord🙏🙏🙏 ",
		image: "/posts/2.jpg",
		date: "39 mins ago",
		userId: 2,
		likes: 99,
		comments: 26,
	},
	{
		id: 3,
		description: "What an amazing festival! Waiting for next time💃💃",
		image: "/posts/3.jpg",
		date: "2hr 39mins ago",
		userId: 3,
		likes: 15,
		comments: 7,
	},
	{
		id: 4,
		description:
			"There is nothing like the smell of nature🏕️ and the feeling of freedom, feeling blessed🙏🙏",
		image: "/posts/4.jpg",
		date: "1d ago",
		userId: 4,
		likes: 123,
		comments: 48,
	},
	{
		id: 5,
		description: "Junk food, the taste of life!🍔😜😜",
		image: "/posts/5.jpg",
		date: "3 mins ago",
		userId: 5,
		likes: 33,
		comments: 4,
	},
	{
		id: 6,
		description: "Peace, love, mountains and calm. Here I come🗻🗻🗻",
		image: "/posts/6.jpg",
		date: "55 mins ago",
		userId: 6,
		likes: 160,
		comments: 88,
	},
	{
		id: 7,
		description:
			"A change in life is welcome, healthy food equals a healthy life🥑🥚🍅🍅",
		image: "/posts/7.jpg",
		date: "15 mins ago",
		userId: 7,
		likes: 20,
		comments: 4,
	},
	{
		id: 8,
		description: "An evening full of lights and lots of fun🎡",
		image: "/posts/8.jpg",
		date: "45sec ago",
		userId: 8,
		likes: 3,
		comments: 1,
	},
	{
		id: 9,
		description: "Final preparations !! Tokyo🗼🗼 here we come😜",
		image: "/posts/9.jpg",
		date: "3h ago",
		userId: 9,
		likes: 100,
		comments: 36,
	},
	{
		id: 10,
		description: "Hard work, yields good things💍💍",
		image: "/posts/10.jpg",
		date: "50 mins ago",
		userId: 10,
		likes: 30,
		comments: 19,
	},
];
